version: 2.1

workflows:
  # workflow name (can be anything)
  deploy:
    # jobs to be executed in this workflow
    jobs:
      - checkout_code
      - install
      - test

references:
  node_defaults: &node_defaults # working_directory: ~/repo
    docker:
      # execution environment "docker"
      - image: cimg/node:18.0.0
    resource_class: small

jobs:
  # job called "checkout_code" (can be anything)
  checkout_code:
    <<: *node_defaults
    steps:
      - checkout
  install:
    <<: *node_defaults
    steps:
      - run:
          name: Install dependencies
          command: npm install
  unit_tests:
    <<: *node_defaults
    steps:
      - run:
          name: Run Tests
          command: npm test

  # test:
  #   # execution environment "docker"
  #   docker:
  #     - image: cimg/node:18.0.0
  #   steps:
  #     - checkout
  #     - run:
  #         name: Install dependencies
  #         command: npm install
  #     - run:
  #         name: Run Tests
  #         command: npm test
